[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl"]

[phases.install]
cmds = ["echo 'PHP installed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
